### ISSUE TITLE
RuntimeError: missing networks: drupalvm

### ISSUE THREAD

**Issue by korzh-nick** [korzh-nick/drupal-vm#2]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
ansible [core 2.12.4]
podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1

```

### Your OS

 - **Linux** Archlinux

### Full console output

```
podman-compose up -d
['podman', '--version', '']
using podman version: 4.1.1
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: drupalvm
```
### Summary
networks option not working in docker-compose

**Comment by korzh-nick** [comment]
1f84cf59a779d87a5c871012483f96e02e75514b

**Comment by korzh-nick** [comment]
as far as I understand networks is not supported in podman-compose
https://github.com/aramean/go-podman-compose/wiki/Compose-compatibility

**Comment by korzh-nick** [comment]
8f4c01d8fd4635e03cfd67a3f2a7a04e0832241b
